###findAll
GET http://localhost:8080/giftCertificates
Accept: application/json

###findById
GET http://localhost:8080/giftCertificates/1
Accept: application/json

###save
POST http://localhost:8080/giftCertificates
Content-Type: application/json

{
  "name": "Gift",
  "description": "Very Big",
  "price": 10,
  "duration": 3,
  "tags": [
    {
      "name": "Coca-cola"
    },
    {
      "name": "Sprite"
    }
  ]
}

###update
PUT http://localhost:8080/giftCertificates
Content-Type: application/json

{
  "id": 1,
  "name": "Salsa",
  "description": "Little",
  "price": 10,
  "duration": 3
}

###delete
DELETE http://localhost:8080/giftCertificates/2
Content-Type: application/json
