###makeAnOrder
POST http://localhost:8080/orders
Content-Type: application/json

{
  "user_id": 2,
  "gift_ids": [
    1,
    2
  ]
}

###findAllUserOrders
GET http://localhost:8080/orders/2?page=0&size=10&sortBy=price
Accept: application/json

###updateUserOrder
PUT http://localhost:8080/orders
Content-Type: application/json

{
  "user_id": 2,
  "order_id": 1,
  "gift_ids": [
    5
  ]
}

###deleteUserOrder
DELETE http://localhost:8080/orders?userId=2&orderId=5
Content-Type: application/json
